class GameConfig():
    # Game
    FPS = 60
    FLIGHT_LEVEL = 216
    LEVEL_WIDTH = 3200
    CAMERA_TARGET_X_RATIO = 0.42

    # Player
    GROUND_LEVEL = 300
    JUMP_IMPULSE = -20
    MOVE_SCALE = 4
    DEATH_ANIMATION_DURATION_MS = 1800
    DEATH_FLOAT_SPEED = 2.2
    DEATH_WOBBLE_AMPLITUDE = 16

    # Screen
    SCREEN_HEIGHT = 400
    SCREEN_WIDTH = 800
    SCREEN_DIMENSION = (SCREEN_WIDTH, SCREEN_HEIGHT)
    PLATFORMER_ASSET_SCALE = 4

    # Menu
    MENU_BACKGROUND_COLOR = (94, 129, 162)
    MENU_TITLE_COLOR = (127, 217, 187)

    # Fly
    FLY_SCORE = 100
    FLY_DAMAGE = 10
    FLY_SPAWN_WEIGHT = 58
    FLY_COMBO_CHANCE = 45
    FLY_COMBO_MIN_SIZE = 2
    FLY_COMBO_MAX_SIZE = 3
    FLY_COMBO_MIN_SPACING = 86
    FLY_COMBO_MAX_SPACING = 122
    DOUBLE_COMBO_SCORE = 1000
    TRIPLE_COMBO_SCORE = 2000
    COMBO_EFFECT_DURATION_MS = 850
    TRIPLE_COMBO_EFFECT_DURATION_MS = 1700
    SCORE_RUNUP_STEP = 10
    SCORE_RUNUP_INTERVAL_MS = 28
    FLOATING_SCORE_DURATION_MS = 1200

    # Snail
    SNAIL_SCORE = 200
    SNAIL_DAMAGE = 14
    STOMPABLE_SNAIL_SPAWN_WEIGHT = 18
    VOLATILE_SNAIL_SPAWN_WEIGHT = 24
    SNAIL_WEAK_SPOT_MARGIN = 20

    # Spawning
    MAX_ACTIVE_MONSTERS = 8
    SPAWN_X_MIN = 900
    SPAWN_X_MAX = 1100

    # Animations
    ANIMATION_SPEED = 0.1
